[book]
title = "Terraform Azurerm Modules"
description = "The example book covers examples."
authors = ["Nick Atkins"]
language = "en"
multilingual = false
src = "docs"

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["custom.css"]

[output.html.search]
limit-results = 15