name: Generate Documentation

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate:
    name: Generate Markdown
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.7'
    - run: go run .
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ORG: openrba
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add documentation files" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: docs
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
