name: Generate Documentation

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate:
    name: Generate Markdown
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.7'
    - run: go run .
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ORG: openrba
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: docs
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
        retention-days: 5
