name: Generate Documentation

on:
  schedule:
    - cron: '30 */11 * * *'
  workflow_dispatch:

jobs:
  generate:
    name: Generate Markdown
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.7'
    - run: go run .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG: openrba
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
        retention-days: 5


  wiki:
    name: Publish Github Wiki
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki # specify the wiki repo name here.
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - name: edit wiki
        run: |
          echo "Success"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated wiki publish"
      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki # specify the wiki repo and push the update.
          github_token: ${{ secrets.GH_TOKEN }}
